import {authenticateRequest} from '@/lib/auth';import {mapOpportunity} from '@/lib/crm-store';import {opportunityInputSchema,validationError} from '@/lib/validation';
export const dynamic='force-dynamic';
const vals=(o:ReturnType<typeof opportunityInputSchema.parse>)=>[o.companyId,o.leadId||null,o.primaryContactId||null,o.name,o.stage,o.value,o.probability,o.closeDate||null,o.owner,o.priority,o.outcome||null,o.archived?1:0];
async function companyExists(db:D1Database,w:string,id:string){return !!await db.prepare('SELECT id FROM companies WHERE workspace_id=? AND id=?').bind(w,id).first()}
async function relationshipsValid(db:D1Database,w:string,data:ReturnType<typeof opportunityInputSchema.parse>){
  if(!await companyExists(db,w,data.companyId))return 'Company not found.';
  if(data.leadId){const lead=await db.prepare('SELECT id FROM leads WHERE workspace_id=? AND id=? AND company_id=?').bind(w,data.leadId,data.companyId).first();if(!lead)return 'Lead does not belong to this company.'}
  if(data.primaryContactId){const contact=await db.prepare('SELECT id FROM contacts WHERE workspace_id=? AND id=? AND company_id=? AND archived=0').bind(w,data.primaryContactId,data.companyId).first();if(!contact)return 'Primary contact does not belong to this company.'}
  return null;
}
export async function POST(request:Request){const a=await authenticateRequest(request,'records:write');if(!a.ok)return a.response;const p=opportunityInputSchema.safeParse(await request.json());if(!p.success)return validationError(p.error);const relationError=await relationshipsValid(a.db,a.session.workspace.id,p.data);if(relationError)return Response.json({error:relationError},{status:422});const id=p.data.id||crypto.randomUUID();await a.db.prepare('INSERT INTO opportunities (id,workspace_id,company_id,lead_id,primary_contact_id,name,stage,value,probability,close_date,owner,priority,outcome,archived) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,a.session.workspace.id,...vals(p.data)).run();const row=await a.db.prepare('SELECT * FROM opportunities WHERE id=? AND workspace_id=?').bind(id,a.session.workspace.id).first<Record<string,unknown>>();return Response.json({opportunity:mapOpportunity(row!)},{status:201})}
export async function PATCH(request:Request){const a=await authenticateRequest(request,'records:write');if(!a.ok)return a.response;const p=opportunityInputSchema.safeParse(await request.json());if(!p.success)return validationError(p.error);if(!p.data.id||!p.data.version)return Response.json({error:'Stable ID and version are required.'},{status:400});const relationError=await relationshipsValid(a.db,a.session.workspace.id,p.data);if(relationError)return Response.json({error:relationError},{status:422});const result=await a.db.prepare('UPDATE opportunities SET company_id=?,lead_id=?,primary_contact_id=?,name=?,stage=?,value=?,probability=?,close_date=?,owner=?,priority=?,outcome=?,archived=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND workspace_id=? AND version=?').bind(...vals(p.data),p.data.id,a.session.workspace.id,p.data.version).run();if(!result.meta.changes)return Response.json({error:'This opportunity changed elsewhere. Refresh and try again.'},{status:409});const row=await a.db.prepare('SELECT * FROM opportunities WHERE id=? AND workspace_id=?').bind(p.data.id,a.session.workspace.id).first<Record<string,unknown>>();return Response.json({opportunity:mapOpportunity(row!)})}
export async function DELETE(request:Request){const a=await authenticateRequest(request,'records:write');if(!a.ok)return a.response;const id=new URL(request.url).searchParams.get('id');if(!id)return Response.json({error:'Opportunity ID is required.'},{status:400});const deps=await a.db.prepare('SELECT (SELECT COUNT(*) FROM tasks WHERE workspace_id=? AND opportunity_id=?)+(SELECT COUNT(*) FROM activities WHERE workspace_id=? AND opportunity_id=?) total').bind(a.session.workspace.id,id,a.session.workspace.id,id).first<{total:number}>();if(Number(deps?.total||0))return Response.json({error:'Archive this opportunity instead; it has linked history.'},{status:409});await a.db.prepare('DELETE FROM opportunities WHERE id=? AND workspace_id=?').bind(id,a.session.workspace.id).run();return Response.json({deleted:id})}
